### ISSUE TITLE
Webserver für Firmware deployment

### ISSUE THREAD

**Issue by indigo423** [freifunk-fulda/gluon#2]
- Einrichten Webserver für Auslieferung der Freifunk-Firmware
- Historie der Firmware für development und stable branches ermöglichen.

**Comment by fooker** [comment]
Läuft schon, oder?

https://firmware.freifunk-fulda.de / https://firmware.services.fffd

**Comment by indigo423** [comment]
We provide https://download.fulda.freifunk.net, this resolve #2.
