### ISSUE TITLE
TP-Link WDR4300 funkt nicht mit 5GHz

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/gluon#4]
Nach der erfolreichen Installation der Firmware auf einem TP-Link WDR4300 v1.7 funktionieren fast alle Funktionen.
Jedoch sendet der Router nur im 2,4GHz Bereich und nicht im 5GHz Bereich.

**Comment by fooker** [comment]
Ich hab gerade keine Hardware hier, die 5 GHz unterstützt. Können wir uns Treffen um das zu testen oder kannst du mir SSH-Access geben?

**Comment by mortzel** [comment]
Die Note ist die 'fffd-grebenhain-bahnhofstr-49' und dein SSH-Key ist dort eingetragen.

**Comment by fooker** [comment]
Sieht so aus als ob der Parameter 'channel' für 'wifi5' nicht richtig aus der site.config übernommen wird:

```
wireless.radio0=wifi-device
wireless.radio0.type=mac80211
wireless.radio0.path=platform/ar934x_wmac
wireless.radio0.diversity=1
wireless.radio0.distance=1000
wireless.radio0.channel=1
wireless.radio0.country=DE
wireless.radio0.htmode=HT40+
wireless.radio0.hwmode=11g
wireless.radio1=wifi-device
wireless.radio1.type=mac80211
wireless.radio1.path=pci0000:00/0000:00:00.0
wireless.radio1.diversity=1
wireless.radio1.distance=1000
wireless.radio1.country=DE
wireless.radio1.htmode=HT40+
wireless.radio1.hwmode=11a
wireless.radio1.channel=1
```

Der Kanal für 'radio1', welches das Device für 5GHz ist steht auch auf 1.

**Comment by fooker** [comment]
Note: Das relevante File ist wohl
https://github.com/freifunk-gluon/packages/blob/2014.4.x/gluon/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/mesh-batman-adv-core/invariant/020-wireless

**Comment by fooker** [comment]
Hm, ich habe das gerade mit einem Gerät hier getestet:
- Von original Firmware auf Freifunk-Fulda (Version stable-2) geflasht
- Im Config-Interface meinen SSH-Key hinterlegt
- Im Config-Interface auf "Speichern & Neustarten" geklickt
- Reboot abgewartet
Und 5 GHz geht bei mir.

Hast du mal eine Neu-Installation der Firmware ohne Übernahme der Settings probiert:
- In Config-Modus booten
- Auf Expert/Firmware-Update klicken
- Firmware Version stable-2 herunterladen und dort angeben
- Harken bei "Einstellungen behalten" wegmachen

**Comment by mortzel** [comment]
Nach der Neu-Installation mit Stable ohne Übernahme der Settings funktiert nun auch 5GHz.
