### ISSUE TITLE
Installieren des Paktes 'gluon-luci-private-wifi' 

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/gluon#5]
Um privates WLAN auf den Nodes über die Web UI zu aktivieren sollte das Paket 'gluon-luci-private-wifi' installiert werden. Jedoch sollte hierbei der Hinweis auftauchen, dass diese nicht in Kombination mit 'Mesh-on-WAN' aktieviert werden sollte.

**Comment by Sheogorath-SI** [comment]
packages are installed in sites config not in gluon package
