### ISSUE TITLE
Systemlast bei TP-Link TL-WR841N/ND v9 mit Gluon 2017.x stark erhöht

### ISSUE THREAD

**Issue by depressivum** [freifunk-fulda/gluon#8]
Problem ist bekannt, aber noch nicht behoben:
https://github.com/freifunk-gluon/gluon/issues/1243#issuecomment-353227388

5-276 / gluon-383af2a läuft derzeit problemlos. Ist es sinnvoll, für die betroffenen Modelle weiterhin die alte Gluon-Version auszurollen, bis das Problem behoben ist? Sonst ist bei aktiviertem Autoupdate kein "zurück" möglich, ohne den Router neu zu flashen.

**Comment by Noodlesalat** [comment]
Wir beschäftigen uns mit dem Problem ab sofort hier: https://github.com/freifunk-fulda/orga/issues/159

Issue hier wird daher geschlossen.
